spring:
    profiles: local

server:
      port: 8080

---

spring:
    profiles: dev

server:
      port: 8080


---

spring:
    profiles: stage

server:
      port: 8080


---

spring:
    profiles: production

server:
      port: 8080

